#!/bin/sh

SCRIPTPATH="$(cd "$(dirname "$0")"; pwd -P)"

# source env
. "$HOME/.config/env"

# Launch XDG autostart applications
[ -f "$SCRIPTPATH/is_reload" ] || {
    for app in "${XDG_CONFIG_HOME:-$HOME/.config}"/autostart/*.desktop; do
        # Universal way to launch .desktop file: https://askubuntu.com/a/664272
        awk '/^Exec=/ {sub("^Exec=", ""); gsub(" ?%[cDdFfikmNnUuv]", ""); exit system($0)}' "$app" &
    done
    for app in /etc/xdg/autostart/*.desktop; do
        # Universal way to launch .desktop file: https://askubuntu.com/a/664272
        awk '/^Exec=/ {sub("^Exec=", ""); gsub(" ?%[cDdFfikmNnUuv]", ""); exit system($0)}' "$app" &
    done
}
[ -f "$SCRIPTPATH/is_reload" ] && rm "$SCRIPTPATH/is_reload"

# allow rootless distrobox GUI
xhost "+si:localuser:$USER"

# ensure sxhkd is running
pgrep -x sxhkd > /dev/null || sxhkd &

bspc rule -a launcher:launcher center=on state=floating sticky=on
bspc rule -a steamwebhelper:steamwebhelper state=floating sticky=on
bspc rule -a Zathura state=tiled # Do not start zathura floating

bspc config border_width 2
bspc config window_gap 14

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true
#bspc config pointer_follows_monitor true

bspc config normal_border_color '#0b0d11'
bspc config active_border_color '#0b0d11'
bspc config focused_border_color '#61afef'

# A host-dependend setup script. An example is in ~/.dotfiles/.config/bspwm/hostconf.example.sh
"$SCRIPTPATH"/hostconf.sh

picom &
dunst &
nitrogen --restore &
pgrep -x polybar > /dev/null || GIT_USERNAME=$(git config user.name) polybar -r &

setxkbmap -layout 'eu,de'
setxkbmap -option 'grp:rctrl_toggle'
setxkbmap -option 'ctrl:nocaps'
numlockx on
xsetroot -cursor_name left_ptr &
